---
- hosts: all
  sudo: yes
  vars_files:
    - vars/webapp.yml
  tasks:
    - name: create app user
      user: name={{app_name}} shell=/bin/bash groups=sudo

    - name: add authorized key
      authorized_key: user={{app_name}} key="{{ lookup('file', pub_key) }}"

    - name: add deploy private key
      copy: src={{ deploy_private_key }} dest=/home/{{ app_name }}/.ssh/id_rsa group={{ app_name }} owner={{ app_name }} mode=0400

    - name: create db
      mysql_db: name="{{ app_name }}_production" login_user=root login_password={{ db_root_pwd }}

    - name: create db user
      mysql_user: name={{ app_name }} password={{ db_pwd }} priv="{{ app_name }}_production.*:ALL" state=present login_user=root login_password={{ db_root_pwd }}

    - name: create nginx conf
      template: src=templates/webapp_nginx.conf dest=/etc/nginx/conf.d/{{app_domain}}.conf owner=root group=root mode=0644

    - name: restart nginx
      service: name=nginx state=restarted
