- name: install mysql
  apt: pkg={{ item }}
  with_items:
      - mysql-server
      - python-mysqldb

- name: change mysql root password
  mysql_user: name=root password={{mysql_root_password}}
  become: no
  ignore_errors: yes
