- name: install ruby build essential
  apt: pkg={{ item }}
  with_items: #https://github.com/wayneeseguin/rvm/blob/master/scripts/functions/requirements/ubuntu
    - g++
    - gcc
    - make
    - libc6-dev
    - patch
    - openssl
    - ca-certificates
    - libreadline6
    - libreadline6-dev
    - curl
    - zlib1g
    - zlib1g-dev
    - libssl-dev
    - libyaml-dev
    - libsqlite3-dev
    - sqlite3
    - autoconf
    - libgdbm-dev
    - libncurses5-dev
    - automake
    - libtool
    - bison
    - pkg-config
    - libffi-dev

- name: download ruby
  get_url: url=https://ruby.taobao.org/mirrors/ruby/{{ ruby_ver }}/ruby-{{ ruby_full_ver }}.tar.gz dest=/tmp/ruby.tar.gz
  become: no

- name: create /tmp/ruby dir
  file: path=/tmp/ruby state=directory
  become: no

- name: untar ruby.tar.gz
  command: tar xf /tmp/ruby.tar.gz chdir=/tmp/ruby
  become: no

- name: configure ruby
  command: ./configure chdir=/tmp/ruby/ruby-{{ ruby_full_ver }} --prefix=/opt/ruby{{ ruby_ver_dir }}
  become: no

- name: make ruby
  command: make chdir=/tmp/ruby/ruby-{{ ruby_full_ver }}
  become: no

- name: install ruby
  command: make install chdir=/tmp/ruby/ruby-{{ ruby_full_ver }}

- name: create ruby etc dir
  file: path=/opt/ruby{{ ruby_ver_dir }}/etc state=directory mode=0755

- name: copy gemrc
  copy: src=../files/gemrc dest=/opt/ruby{{ ruby_ver_dir }}/etc/gemrc

- name: install bundler
  command: /opt/ruby{{ ruby_ver_dir}}/bin/gem install bundler
